odds/urls.py
from django.urls import path

from . import views

app_name = "odds"
urlpatterns = [
    path("", views.odds_home, name="odds_home"),
    path("<str:sport>/", views.sport_odds, name="sport_odds"),
]

sports_bet_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('tracker.urls')),
    path('', include('odds.urls')),
]

tracker/urls.py
from django.urls import path

from . import views

app_name = "tracker"
urlpatterns = [
    path("tracker/", views.tracker, name="track"),
    path("tracker/add", views.create_tracked_bet, name="add_bet"),
    path("tracker/update/<int:tracked_bet_id>", views.update_tracked_bet, name="update_bet"),
    path("tracker/delete/<int:tracked_bet_id>", views.delete_tracked_bet, name="delete_bet"),
]

tracker/models.py
from django.conf import settings
from django.db import models

from .validators import validate_bet_amount, validate_odds


class TrackedBet(models.Model):
    RESULT_CHOICES = (
        ('pending', 'Pending'),
        ('win', 'Win'),
        ('loss', 'Loss'),
        ('void', 'Void'),
    )
    MARKET_CHOICES = (
        ('h2h', 'Moneyline'),
        ('spreads', 'Spread'),
        ('totals', 'Total'),
        ('other', 'Other'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    sportsbook = models.CharField(max_length=50)
    sport = models.CharField(max_length=50)
    market = models.CharField(choices=MARKET_CHOICES, max_length=20, )
    description = models.CharField(max_length=240)
    points = models.FloatField(blank=True, null=True)
    bet_amount = models.FloatField(validators=[validate_bet_amount])
    odds = models.IntegerField(validators=[validate_odds])
    winnings = models.FloatField(blank=True, null=True)
    result = models.CharField(choices=RESULT_CHOICES, default='pending', max_length=20)

    REQUIRED_FIELDS = [ 'user', 'sportsbook', 'sport', 'market', 'description', 'bet_amount', 'odds', 'winnings', 'result' ]

tracker/forms.py
from django import forms

from .models import TrackedBet


class TrackedBetForm(forms.ModelForm):
    class Meta:
        model = TrackedBet
        fields = [ 'sportsbook', 'sport', 'market', 'description', 'points', 'bet_amount', 'odds', 'winnings', 'result' ]

tracker/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .forms import TrackedBetForm
from .models import TrackedBet


@login_required
def tracker(request):
    """ Main page for displaying the tracker table """
    bets = TrackedBet.objects.filter(user=request.user).values()
    profit = get_profit(bets)
    context = {
        "df": bets,
        "add_form": TrackedBetForm(),
        "profit": "%.2f"%profit
    }
    return render(request, "tracker/tracker.html", context)


def get_profit(bets):
    """ Returns the profit for the provided bets based on bet wins and losses """
    profit = 0
    for bet in bets:
        if bet["result"] == 'win':
            profit += bet["winnings"]
            profit += bet["bet_amount"]
        elif bet["result"] == 'loss':
            profit += bet["winnings"]
            profit += bet["bet_amount"]
    return profit


@login_required
def create_tracked_bet(request):
    """ Adds a new bet to the TrackedBet db """
    if request.POST:
        TrackedBet.objects.create(
            user=request.user,
            sportsbook=request.POST["sportsbook"],
            sport=request.POST["sport"],
            market=request.POST["market"],
            description=request.POST["description"],
            points=request.POST["points"],
            bet_amount=request.POST["bet_amount"],
            odds=request.POST["odds"],
            winnings=request.POST["winnings"],
            result=request.POST["result"],
        )
    return HttpResponseRedirect(reverse("tracker:track"))


@login_required
def update_tracked_bet(request, tracked_bet_id):
    """ Updates and existing bet in the TrackedBet db """
    if request.POST:
        TrackedBet.objects.filter(id=tracked_bet_id).update(
            sportsbook=request.POST["sportsbook"],
            sport=request.POST["sport"],
            market=request.POST["market"],
            description=request.POST["description"],
            points=request.POST["points"],
            bet_amount=request.POST["bet_amount"],
            odds=request.POST["odds"],
            winnings=request.POST["winnings"],
            result=request.POST["result"],
        )
        return HttpResponseRedirect(reverse("tracker:track"))
    bet = TrackedBet.objects.get(id=tracked_bet_id)
    context = {
        "form": TrackedBetForm(instance=bet),
        "bet_id": tracked_bet_id,
    }
    return render(request, "tracker/update.html", context)


@login_required
def delete_tracked_bet(request, tracked_bet_id):
    """ Deletes a bet from the TrackedBet db """
    bet = get_object_or_404(TrackedBet, pk=tracked_bet_id)
    bet.delete()
    return HttpResponseRedirect(reverse("tracker:track"))

tracker/templates/tracker/tracker.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Tracker{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="m-3">
            <h3>Profit: ${{profit}}</h3>
        </div>
        <div class="row justify-content-center">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary m-1" data-toggle="modal" data-target="#addBet">Add Bet</button>

            <!-- Modal -->
            <div class="modal fade" id="addBet" tabindex="-1" role="dialog" aria-labelledby="addBetTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="addBetTitle">Add Bet</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <form class="mt-3 mb-3" method="post" action="{% url 'tracker:add_bet' %}">
                        {% csrf_token %}
                        {% for field in add_form %}
                            <div class="form-group justify-content-center">
                                {% if field.errors %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger w-25 m-auto" >{{ error }}</div>
                                {% endfor %}
                                {% endif %}
                                <label for="{{field.auto_id}}" class="col-2 col-form-label">{{field.label}}:</label>
                                {{field}}
                            </div>
                        {% endfor %}
                        <input type="submit" value="Add Bet" class="mt-2 btn btn-success">
                    </form>
                </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-4">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>Sport</th>
                        <th>Sportsbook</th>
                        <th>Market</th>
                        <th>Description</th>
                        <th>Points</th>
                        <th>Bet Amount</th>
                        <th>Odds</th>
                        <th>Winnings</th>
                        <th>Result</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in df %}
                        <tr>
                            <td>{{row.sport}}</td>
                            <td>{{row.sportsbook}}</td>
                            <td>{{row.market}}</td>
                            <td>{{row.description}}</td>
                            <td>{{row.points}}</td>
                            <td>{{row.bet_amount}}</td>
                            <td>{{row.odds}}</td>
                            <td>{{row.winnings}}</td>
                            <td>{{row.result}}</td>
                            <td><a href="{% url 'tracker:update_bet' row.id %}"><button type="button" class="btn btn-primary"><i class='fa fa-solid fa-edit' style='color: white'></i></button></a></td>
                            <td>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteBet{{row.id}}"><i class='fa fa-solid fa-trash-can' style='color: white'></i></button>

                                <!-- Modal -->
                                <div class="modal fade" id="deleteBet{{row.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteBetTitle" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="deleteBetTitle">Are you sure you want to delete this bet?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <form method="post" action="{% url 'tracker:delete_bet' row.id %}">
                                                {% csrf_token %}
                                                <div class="modal-footer">
                                                    <input type="submit" value="Confirm" class="btn btn-primary">
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

tracker/templates/tracker/update.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Update Bet{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <form class="mt-3 mb-3" method="post" action="{% url 'tracker:update_bet' bet_id %}">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group justify-content-center">
                    {% if field.errors %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger w-25 m-auto" >{{ error }}</div>
                    {% endfor %}
                    {% endif %}
                    <label for="{{field.auto_id}}" class="col-2 col-form-label">{{field.label}}:</label>
                    {{field}}
                </div>
            {% endfor %}
            <input type="submit" value="Update Bet" class="mt-2 btn btn-success">
        </form>
    </div>
{% endblock %}