odds/urls.py
from django.urls import path

from . import views

app_name = "odds"
urlpatterns = [
    path("", views.odds_home, name="odds_home"),
    path("<str:sport>/", views.sport_odds, name="sport_odds"),
]

sports_bet_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('tracker.urls')),
    path('', include('odds.urls')),
]

tracker/urls.py
from django.urls import path

from . import views

app_name = "tracker"
urlpatterns = [
    path("tracker/", views.tracker, name="track"),
    path("tracker/add", views.create_tracked_bet, name="add_bet"),
    path("tracker/update/<int:tracked_bet_id>", views.update_tracked_bet, name="update_bet"),
    path("tracker/delete/<int:tracked_bet_id>", views.delete_tracked_bet, name="delete_bet"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .forms import CustomLoginForm
from .views import SignUpView


app_name = "users"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", LoginView.as_view(authentication_form=CustomLoginForm), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="/" class="text-light btn"><h1>Odd Comparison and Bet Tracking</h1></a>
        <section class="row">
            {% if request.user.is_authenticated %}
                {% if request.user.first_name %}
                    <h3 class="text-light mx-2 text-lg-left">{{request.user.first_name}}</h3>
                {% endif %}
                <a href="{% url 'users:logout' %}"><button class="btn btn-outline-light mx-2">Log Out</button></a>
            {% else %}
                <a href="{% url 'users:login' %}"><button class="btn btn-lg btn-outline-light mx-2">Log In</button></a>
                <a href="{% url 'users:signup' %}"><button class="btn btn-lg btn-outline-light mx-2">Sign Up</button></a>
            {% endif %}
        </section>
    </nav>
    <section class="content container text-center">
    <header>
        {% block header %}{% endblock %}
    </header>
    {% for message in messages %}
        <div class="alert alert-danger w-25 m-auto" >{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
    </section>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Home{% endblock %}</h1>
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="container">
            <div class="col">
                {% for sport in sports %}
                    <a href="{% url 'odds:sport_odds' sport.title %}"><button class="btn btn-primary m-2">{{sport.title}}</button></a>
                {% endfor %}
            </div>
            <div class="col">
                <a href="{% url 'tracker:track' %}"><button class="btn btn-success m-4">Bet Tracker</button></a>
            </div>
        </div>
    {% else %}
        <h2 class="my-5">Sign In to Compare Odds and Track Bets</h2>
    {% endif %}
{% endblock %}